--- #YAML:1.0
name:                OODoc-Template
version:             0.1
abstract:            Simple template system
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::More:                    0.47
    Test::Pod:                     1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mark Overmeer
